name: 403 Bypass Scanner
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'
jobs:
  scan:
    uses: ./.github/workflows/scan-template.yml
    with:
      scan_name: "403 Bypass"
      tags: "403"
      httpx_flags: "-silent -mc 403"
    secrets:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
