name: Exposed Git and Env Scanner
on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'
jobs:
  scan:
    uses: ./.github/workflows/scan-template.yml
    with:
      scan_name: "Git/Env Exposure"
      tags: "git,env-file,config"
    secrets:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
