name: Exposed Jenkins Grafana Kibana Scanner
on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'
jobs:
  scan:
    uses: ./.github/workflows/scan-template.yml
    with:
      scan_name: "Jenkins/Grafana/Kibana"
      tags: "jenkins,grafana,kibana"
    secrets:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
