name: Prototype Pollution Scanner
on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *'
jobs:
  scan:
    uses: ./.github/workflows/scan-template.yml
    with:
      scan_name: "Prototype Pollution"
      tags: "prototype-pollution"
    secrets:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
