name: S3 Bucket Scanner
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
jobs:
  scan:
    uses: ./.github/workflows/scan-template.yml
    with:
      scan_name: "S3 Bucket Misconfiguration"
      tags: "aws-s3,s3"
    secrets:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
