name: Exposed Secrets Scanner
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'
jobs:
  scan:
    uses: ./.github/workflows/scan-template.yml
    with:
      scan_name: "Exposed Secrets"
      tags: "token,secret,api-key"
      use_katana: true
      nuclei_input: "urls"
    secrets:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
