name: Exposed Swagger API Docs Scanner
on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'
jobs:
  scan:
    uses: ./.github/workflows/scan-template.yml
    with:
      scan_name: "Exposed API Docs"
      tags: "swagger,api-docs,openapi"
    secrets:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
